version: "3.9"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            SA_PASSWORD: "Platanios1234"
            ACCEPT_EULA: "Y"
        ports:
            - "49301:4000"
    my_web_site:
        image: my_web_site
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "49501:80"
        depends_on:
            - db
        command: ["dotnet", "ef", "database update"]