// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebSite.Data;

namespace MyWebSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220225131709_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MyWebSite.Areas.Identity.Data.MyWebSiteRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ad376a8f-9eab-4bb9-9fca-30b01540f445",
                            ConcurrencyStamp = "48a89cd5-4fba-4eff-ad86-1019bce98909",
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 554, DateTimeKind.Local).AddTicks(1664),
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("MyWebSite.Areas.Identity.Data.MyWebSiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfingPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aba3ec62-84f1-433d-90fb-93242b927157",
                            ConfingPassword = "-Platanios719791",
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 554, DateTimeKind.Local).AddTicks(6908),
                            Email = "alexandrosplatanios15@gmail.com",
                            EmailConfirmed = false,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "alexandrosplatanios15@gmail.com",
                            NormalizedUserName = "alexandrosplatanios15@gmail.com",
                            Password = "-Platanios719791",
                            PasswordHash = "AQAAAAEAACcQAAAAED3cUB82hoKPqnfyJYvL2qj+O1gJd2tCooZfoiGvlQHClsB8ITw+1e635xyizzS9lA==",
                            PhoneNumber = "6949277783",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "alexandrosplatanios15@gmail.com"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVFullPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CVPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVPath = "/CV/CV.pdf",
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 542, DateTimeKind.Local).AddTicks(7502),
                            Description = "My CV",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 547, DateTimeKind.Local).AddTicks(5078)
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.ContactData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedLin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Fleming 14, Voula, 16673, Greece",
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 553, DateTimeKind.Local).AddTicks(3481),
                            Email = "alexandrosplatanios28@gmail.com",
                            FacebookLink = "https://www.facebook.com/profile.php?id=100013059701658",
                            FullName = "Alexandros Platanios",
                            InstagramLink = "https://www.instagram.com/alexandros_platanios/",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 552, DateTimeKind.Local).AddTicks(6986),
                            LinkedLin = "https://www.linkedin.com/in/alexandros-platanios-723984203/",
                            Phone = "+30-6949277783",
                            SubTitle = "Do you have any questions? Please do not hesitate to contact ME directly.I'll come back to you within a matter of hours to help you.",
                            Title = "Contact us"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.HomeData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFullPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Paragraph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HomeData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 552, DateTimeKind.Local).AddTicks(4924),
                            ImageFullPath = "",
                            ImagePath = "/img/home/me.jpg",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 552, DateTimeKind.Local).AddTicks(679),
                            Paragraph = "The first book I started with was C++ at the age of 15, but only as a hobby. When I was 18 I started working at a local gym as an instructor and I stayed in that field for 7 years. Right after that a friend of mine that is a programmer saw a code I made for my motorcycle and encouraged me to pursue programming.",
                            SubTitle = "A bot about me",
                            Title = "Hello"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageFullPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(6839),
                            ImagePath = "~/ProjectImages/CBProject/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(7309),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6480),
                            ImagePath = "~/ProjectImages/CBProject/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6513),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6633),
                            ImagePath = "~/ProjectImages/CBProject/img_3.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6648),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6720),
                            ImagePath = "~/ProjectImages/CBProject/img_4.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(6739),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(7978),
                            ImagePath = "~/ProjectImages/CBProject/img_5.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8001),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8119),
                            ImagePath = "~/ProjectImages/CBProject/img_6.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8132),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8203),
                            ImagePath = "~/ProjectImages/CBProject/img_7.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8213),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8611),
                            ImagePath = "~/ProjectImages/CBProject/img_8.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8668),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8745),
                            ImagePath = "~/ProjectImages/CBProject/img_9.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8765),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8843),
                            ImagePath = "~/ProjectImages/CBProject/img_10.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8855),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8949),
                            ImagePath = "~/ProjectImages/CBProject/img_11.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(8961),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9221),
                            ImagePath = "~/ProjectImages/CBProject/img_12.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9234),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9305),
                            ImagePath = "~/ProjectImages/CBProject/img_13.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9316),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9380),
                            ImagePath = "~/ProjectImages/CBProject/img_14.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9393),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 15,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9462),
                            ImagePath = "~/ProjectImages/CBProject/img_15.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9476),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 16,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9744),
                            ImagePath = "~/ProjectImages/CBProject/img_16.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9766),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 17,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9856),
                            ImagePath = "~/ProjectImages/CBProject/img_17.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9870),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 18,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9957),
                            ImagePath = "~/ProjectImages/CBProject/img_18.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 550, DateTimeKind.Local).AddTicks(9971),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 19,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(228),
                            ImagePath = "~/ProjectImages/CBProject/img_19.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(249),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 20,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(334),
                            ImagePath = "~/ProjectImages/CBProject/img_20.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(347),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 21,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(412),
                            ImagePath = "~/ProjectImages/CBProject/img_21.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(425),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 22,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(491),
                            ImagePath = "~/ProjectImages/CBProject/img_22.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(507),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 23,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(582),
                            ImagePath = "~/ProjectImages/CBProject/img_23.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(593),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 24,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(682),
                            ImagePath = "~/ProjectImages/CBProject/img_24.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(711),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 25,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(823),
                            ImagePath = "~/ProjectImages/CBProject/img_25.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(840),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 26,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(930),
                            ImagePath = "~/ProjectImages/CBProject/img_26.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(944),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 27,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1141),
                            ImagePath = "~/ProjectImages/CBProject/img_27.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1154),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 28,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1234),
                            ImagePath = "~/ProjectImages/CBProject/img_28.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1252),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 29,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1323),
                            ImagePath = "~/ProjectImages/CBProject/img_29.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1337),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 30,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1412),
                            ImagePath = "~/ProjectImages/CBProject/img_30.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1425),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 31,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1490),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1501),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 32,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1567),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1578),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 33,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1654),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_3.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1669),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 34,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1736),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_4.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1747),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 35,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1819),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_5.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1834),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 36,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1900),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_6.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1913),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 37,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(1992),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_7.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2005),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 38,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2072),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_8.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2085),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 39,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2150),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_9.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2162),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 40,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2232),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_10.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2248),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 41,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2323),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_11.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2338),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 42,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2478),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_12.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2491),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 43,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2561),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_13.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2573),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 44,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2654),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_14.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2667),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 45,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2732),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_15.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2744),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 46,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2814),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_1.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2829),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 47,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2904),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_2.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2918),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 48,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(2999),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_3.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3011),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 49,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3073),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_4.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3085),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 50,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3158),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_5.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3170),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 51,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3238),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_6.jpg",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3250),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 52,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3319),
                            ImagePath = "~/ProjectImages/Economy/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3336),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 53,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3408),
                            ImagePath = "~/ProjectImages/Economy/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3420),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 54,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3488),
                            ImagePath = "~/ProjectImages/Economy/img_3.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3501),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 55,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3572),
                            ImagePath = "~/ProjectImages/Economy/img_4.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3587),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 56,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3653),
                            ImagePath = "~/ProjectImages/Economy/img_5.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3667),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 57,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3802),
                            ImagePath = "~/ProjectImages/Economy/img_6.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3819),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 58,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3892),
                            ImagePath = "~/ProjectImages/Economy/img_7.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(3904),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 59,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4289),
                            ImagePath = "~/ProjectImages/Elementum/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4313),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 60,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4408),
                            ImagePath = "~/ProjectImages/Elementum/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4420),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 61,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4507),
                            ImagePath = "~/ProjectImages/Elementum/img_3.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4527),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 62,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4614),
                            ImagePath = "~/ProjectImages/Elementum/img_4.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4628),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 63,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4713),
                            ImagePath = "~/ProjectImages/Elementum/img_5.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4735),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 64,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4827),
                            ImagePath = "~/ProjectImages/Elementum/img_6.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4838),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 65,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4900),
                            ImagePath = "~/ProjectImages/Elementum/img_7.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4912),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 66,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(4988),
                            ImagePath = "~/ProjectImages/Elementum/img_8.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5000),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 67,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5064),
                            ImagePath = "~/ProjectImages/Elementum/img_9.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5076),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 68,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5144),
                            ImagePath = "~/ProjectImages/Elementum/img_10.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5156),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 69,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5311),
                            ImagePath = "~/ProjectImages/Elementum/img_11.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5322),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 70,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5383),
                            ImagePath = "~/ProjectImages/Elementum/img_12.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5395),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 71,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5542),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5555),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 72,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5621),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5633),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 73,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5693),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_3.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5705),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 74,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5766),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_4.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5778),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 75,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5838),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_5.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5849),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 76,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5909),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_6.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(5922),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 77,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6302),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_7.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6333),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 78,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6459),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_8.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6478),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 79,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6568),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_9.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6586),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 80,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6680),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_10.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6698),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 81,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6787),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_11.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6807),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 82,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6895),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_12.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6909),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 83,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(6997),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_13.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7016),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 84,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7102),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_14.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7121),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 85,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7209),
                            ImagePath = "~/ProjectImages/ElevatorDashboard/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7230),
                            ProjectId = 7
                        },
                        new
                        {
                            ID = 86,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7399),
                            ImagePath = "~/ProjectImages/ElevatorDashboard/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7421),
                            ProjectId = 7
                        },
                        new
                        {
                            ID = 87,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7513),
                            ImagePath = "~/ProjectImages/RemoteAutoMoto/img_1.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7528),
                            ProjectId = 8
                        },
                        new
                        {
                            ID = 88,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7617),
                            ImagePath = "~/ProjectImages/RemoteAutoMoto/img_2.png",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 551, DateTimeKind.Local).AddTicks(7636),
                            ProjectId = 8
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadLinkTar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadLinkZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebPage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(1497),
                            Description = "CBProject * ASP .NET FRAMEWORK * 2020/2021 * Online Course Platform:The customer can watch video tutorials or read ebooks.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/CBProject/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/CBProject/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(2004),
                            Price = 5.00m,
                            Title = "CBProject"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5189),
                            Description = "IPCameras Dashborad * .NET CORE (WPF) * 2018/2019 * ESP32-CAM Dashboard:Support all model esp32 and a lot of markets ip cameras.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ESP32-Cam-Dashboard/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ESP32-Cam-Dashboard/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5202),
                            Price = 5.00m,
                            Title = "IPCameras Dashboard"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5247),
                            Description = "IPCameras Chip Software * ESP32 * C++:Frace Detaction + Face Recognition + Alerts + Effects",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ESP32-Cam/archive/refs/tags/v0.1.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ESP32-Cam/archive/refs/tags/v0.1.zip",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5256),
                            Price = 0m,
                            Title = "IPCameras Chip Software * ESP32 * C++:"
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5293),
                            Description = "Salesforce App To Manipulate Your Wallet.",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5301),
                            Price = 0m,
                            Title = "Economy"
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5414),
                            Description = "WordPress WebSite For KungFou School.",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5423),
                            Price = 0m,
                            Title = "Eelementum",
                            WebPage = "https://elementumartialfitness.com"
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5940),
                            Description = "A B&B App on Salesforce For Elevator Maintence Company.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ElevatorsManagement/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ElevatorsManagement/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5952),
                            Price = 0m,
                            Title = "Elevators Managment"
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(5991),
                            Description = "A B&B App writen in Java For Elevator Maintence Company.",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(6000),
                            Price = 0m,
                            Title = "Elevators Dashboard"
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(6036),
                            Description = "Update Your Old Vichecle To Full Software Update.",
                            LastUpdateDate = new DateTime(2022, 2, 25, 15, 17, 8, 549, DateTimeKind.Local).AddTicks(6044),
                            Price = 0m,
                            Title = "Remote Auto Moto"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Image", b =>
                {
                    b.HasOne("MyWebSite.Data.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Order", b =>
                {
                    b.HasOne("MyWebSite.Data.Models.Project", "Project")
                        .WithMany("Orders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Project", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
