// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebSite.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MyWebSite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220304200159_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            RoleId = "ad376a8f-9eab-4bb9-9fca-30b01540f445"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MyWebSite.Areas.Identity.Data.MyWebSiteRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "ad376a8f-9eab-4bb9-9fca-30b01540f445",
                            ConcurrencyStamp = "53805357-ab16-430f-ab57-720443b1a1c4",
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 292, DateTimeKind.Local).AddTicks(9263),
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("MyWebSite.Areas.Identity.Data.MyWebSiteUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("ConfingPassword")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "a18be9c0-aa65-4af8-bd17-00bd9344e575",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa604f4c-eb3a-4315-8c79-a8eaf1d58d5c",
                            ConfingPassword = "-Platanios719791",
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 293, DateTimeKind.Local).AddTicks(3549),
                            Email = "alexandrosplatanios15@gmail.com",
                            EmailConfirmed = false,
                            LastUpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedEmail = "alexandrosplatanios15@gmail.com",
                            NormalizedUserName = "alexandrosplatanios15@gmail.com",
                            Password = "-Platanios719791",
                            PasswordHash = "AQAAAAEAACcQAAAAECgfDCmsCECNwIrVO1+wUnZ10SNXHy05Pg3jm/lFte86kyK4de5UkbFfVTrr0zap7w==",
                            PhoneNumber = "6949277783",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "alexandrosplatanios15@gmail.com"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CVFullPath")
                        .HasColumnType("text");

                    b.Property<string>("CVPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("CVs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CVPath = "/CV/CV.pdf",
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 285, DateTimeKind.Local).AddTicks(2049),
                            Description = "My CV",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 288, DateTimeKind.Local).AddTicks(6257)
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.ContactData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LinkedLin")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ContactData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Fleming 14, Voula, 16673, Greece",
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 292, DateTimeKind.Local).AddTicks(3276),
                            Email = "alexandrosplatanios28@gmail.com",
                            FacebookLink = "https://www.facebook.com/profile.php?id=100013059701658",
                            FullName = "Alexandros Platanios",
                            InstagramLink = "https://www.instagram.com/alexandros_platanios/",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(8992),
                            LinkedLin = "https://www.linkedin.com/in/alexandros-platanios-723984203/",
                            Phone = "+30-6949277783",
                            SubTitle = "Do you have any questions? Please do not hesitate to contact ME directly.I'll come back to you within a matter of hours to help you.",
                            Title = "Contact us"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.HomeData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFullPath")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Paragraph")
                        .HasColumnType("text");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("HomeData");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(7570),
                            ImageFullPath = "",
                            ImagePath = "/img/home/me.jpg",
                            IsActive = true,
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(4731),
                            Paragraph = "The first book I started with was C++ at the age of 15, but only as a hobby. When I was 18 I started working at a local gym as an instructor and I stayed in that field for 7 years. Right after that a friend of mine that is a programmer saw a code I made for my motorcycle and encouraged me to pursue programming.",
                            SubTitle = "A bot about me",
                            Title = "Hello"
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageFullPath")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(6190),
                            ImagePath = "~/ProjectImages/CBProject/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(6608),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8469),
                            ImagePath = "~/ProjectImages/CBProject/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8483),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8538),
                            ImagePath = "~/ProjectImages/CBProject/img_3.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8547),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8595),
                            ImagePath = "~/ProjectImages/CBProject/img_4.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8604),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8650),
                            ImagePath = "~/ProjectImages/CBProject/img_5.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8659),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8708),
                            ImagePath = "~/ProjectImages/CBProject/img_6.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8717),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8762),
                            ImagePath = "~/ProjectImages/CBProject/img_7.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8770),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8815),
                            ImagePath = "~/ProjectImages/CBProject/img_8.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8824),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 9,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8869),
                            ImagePath = "~/ProjectImages/CBProject/img_9.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8877),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 10,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8924),
                            ImagePath = "~/ProjectImages/CBProject/img_10.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(8933),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 11,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9037),
                            ImagePath = "~/ProjectImages/CBProject/img_11.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9047),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 12,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9097),
                            ImagePath = "~/ProjectImages/CBProject/img_12.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9106),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 13,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9153),
                            ImagePath = "~/ProjectImages/CBProject/img_13.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9161),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 14,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9207),
                            ImagePath = "~/ProjectImages/CBProject/img_14.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9216),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 15,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9261),
                            ImagePath = "~/ProjectImages/CBProject/img_15.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9269),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 16,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9314),
                            ImagePath = "~/ProjectImages/CBProject/img_16.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9323),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 17,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9367),
                            ImagePath = "~/ProjectImages/CBProject/img_17.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9376),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 18,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9424),
                            ImagePath = "~/ProjectImages/CBProject/img_18.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9432),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 19,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9478),
                            ImagePath = "~/ProjectImages/CBProject/img_19.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9486),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 20,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9532),
                            ImagePath = "~/ProjectImages/CBProject/img_20.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9541),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 21,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9585),
                            ImagePath = "~/ProjectImages/CBProject/img_21.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9594),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 22,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9639),
                            ImagePath = "~/ProjectImages/CBProject/img_22.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9648),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 23,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9693),
                            ImagePath = "~/ProjectImages/CBProject/img_23.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9701),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 24,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9747),
                            ImagePath = "~/ProjectImages/CBProject/img_24.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9755),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 25,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9800),
                            ImagePath = "~/ProjectImages/CBProject/img_25.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9809),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 26,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9901),
                            ImagePath = "~/ProjectImages/CBProject/img_26.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9911),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 27,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9961),
                            ImagePath = "~/ProjectImages/CBProject/img_27.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(9970),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 28,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(15),
                            ImagePath = "~/ProjectImages/CBProject/img_28.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(23),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 29,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(68),
                            ImagePath = "~/ProjectImages/CBProject/img_29.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(77),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 30,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(121),
                            ImagePath = "~/ProjectImages/CBProject/img_30.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(130),
                            ProjectId = 1
                        },
                        new
                        {
                            ID = 31,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(175),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(184),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 32,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(230),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(239),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 33,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(283),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_3.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(292),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 34,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(339),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_4.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(348),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 35,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(392),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_5.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(400),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 36,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(445),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_6.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(453),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 37,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(498),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_7.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(507),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 38,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(552),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_8.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(560),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 39,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(605),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_9.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(614),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 40,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(659),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_10.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(667),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 41,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(767),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_11.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(776),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 42,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(822),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_12.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(830),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 43,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(875),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_13.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(884),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 44,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(928),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_14.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(937),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 45,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(982),
                            ImagePath = "~/ProjectImages/IPCamerasDashboard/img_15.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(990),
                            ProjectId = 2
                        },
                        new
                        {
                            ID = 46,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1036),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_1.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1044),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 47,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1090),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_2.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1099),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 48,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1143),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_3.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1152),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 49,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1196),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_4.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1205),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 50,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1250),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_5.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1258),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 51,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1302),
                            ImagePath = "~/ProjectImages/IPCamerasESP32/img_6.jpg",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1310),
                            ProjectId = 3
                        },
                        new
                        {
                            ID = 52,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1355),
                            ImagePath = "~/ProjectImages/Economy/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1364),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 53,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1409),
                            ImagePath = "~/ProjectImages/Economy/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1417),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 54,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1462),
                            ImagePath = "~/ProjectImages/Economy/img_3.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1471),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 55,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1515),
                            ImagePath = "~/ProjectImages/Economy/img_4.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1523),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 56,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1619),
                            ImagePath = "~/ProjectImages/Economy/img_5.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1629),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 57,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1679),
                            ImagePath = "~/ProjectImages/Economy/img_6.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1687),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 58,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1732),
                            ImagePath = "~/ProjectImages/Economy/img_7.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1741),
                            ProjectId = 4
                        },
                        new
                        {
                            ID = 59,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1786),
                            ImagePath = "~/ProjectImages/Elementum/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1795),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 60,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1841),
                            ImagePath = "~/ProjectImages/Elementum/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1849),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 61,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1893),
                            ImagePath = "~/ProjectImages/Elementum/img_3.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1902),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 62,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1945),
                            ImagePath = "~/ProjectImages/Elementum/img_4.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1954),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 63,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(1997),
                            ImagePath = "~/ProjectImages/Elementum/img_5.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2005),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 64,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2049),
                            ImagePath = "~/ProjectImages/Elementum/img_6.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2057),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 65,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2102),
                            ImagePath = "~/ProjectImages/Elementum/img_7.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2110),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 66,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2158),
                            ImagePath = "~/ProjectImages/Elementum/img_8.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2167),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 67,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2211),
                            ImagePath = "~/ProjectImages/Elementum/img_9.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2220),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 68,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2263),
                            ImagePath = "~/ProjectImages/Elementum/img_10.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2271),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 69,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2315),
                            ImagePath = "~/ProjectImages/Elementum/img_11.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2324),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 70,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2417),
                            ImagePath = "~/ProjectImages/Elementum/img_12.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2426),
                            ProjectId = 5
                        },
                        new
                        {
                            ID = 71,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2473),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2482),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 72,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2527),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2535),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 73,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2580),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_3.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2588),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 74,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2632),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_4.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2641),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 75,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2685),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_5.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2694),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 76,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2738),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_6.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2747),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 77,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2791),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_7.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2799),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 78,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2844),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_8.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2852),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 79,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2896),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_9.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2905),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 80,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2949),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_10.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(2957),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 81,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3002),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_11.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3010),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 82,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3055),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_12.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3063),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 83,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3108),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_13.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3116),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 84,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3161),
                            ImagePath = "~/ProjectImages/ElevatorManagment/img_14.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3169),
                            ProjectId = 6
                        },
                        new
                        {
                            ID = 85,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3287),
                            ImagePath = "~/ProjectImages/ElevatorDashboard/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3296),
                            ProjectId = 7
                        },
                        new
                        {
                            ID = 86,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3348),
                            ImagePath = "~/ProjectImages/ElevatorDashboard/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3357),
                            ProjectId = 7
                        },
                        new
                        {
                            ID = 87,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3403),
                            ImagePath = "~/ProjectImages/RemoteAutoMoto/img_1.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3412),
                            ProjectId = 8
                        },
                        new
                        {
                            ID = 88,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3458),
                            ImagePath = "~/ProjectImages/RemoteAutoMoto/img_2.png",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 291, DateTimeKind.Local).AddTicks(3466),
                            ProjectId = 8
                        });
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MyMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderID")
                        .HasColumnType("text");

                    b.Property<string>("PayerID")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DownloadLinkTar")
                        .HasColumnType("text");

                    b.Property<string>("DownloadLinkZip")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebPage")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(1264),
                            Description = "CBProject * ASP .NET FRAMEWORK * 2020/2021 * Online Course Platform:The customer can watch video tutorials or read ebooks.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/CBProject/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/CBProject/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(1710),
                            Price = 5.00m,
                            Title = "CBProject"
                        },
                        new
                        {
                            ID = 2,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4664),
                            Description = "IPCameras Dashborad * .NET CORE (WPF) * 2018/2019 * ESP32-CAM Dashboard:Support all model esp32 and a lot of markets ip cameras.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ESP32-Cam-Dashboard/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ESP32-Cam-Dashboard/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4680),
                            Price = 5.00m,
                            Title = "IPCameras Dashboard"
                        },
                        new
                        {
                            ID = 3,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4786),
                            Description = "IPCameras Chip Software * ESP32 * C++:Frace Detaction + Face Recognition + Alerts + Effects",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ESP32-Cam/archive/refs/tags/v0.1.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ESP32-Cam/archive/refs/tags/v0.1.zip",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4795),
                            Price = 0m,
                            Title = "IPCameras Chip Software * ESP32 * C++:"
                        },
                        new
                        {
                            ID = 4,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4838),
                            Description = "Salesforce App To Manipulate Your Wallet.",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4847),
                            Price = 0m,
                            Title = "Economy"
                        },
                        new
                        {
                            ID = 5,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4884),
                            Description = "WordPress WebSite For KungFou School.",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(4892),
                            Price = 0m,
                            Title = "Eelementum",
                            WebPage = "https://elementumartialfitness.com"
                        },
                        new
                        {
                            ID = 6,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5361),
                            Description = "A B&B App on Salesforce For Elevator Maintence Company.",
                            DownloadLinkTar = "https://github.com/Alexandros5880/ElevatorsManagement/archive/refs/tags/v1.0.tar.gz",
                            DownloadLinkZip = "https://github.com/Alexandros5880/ElevatorsManagement/archive/refs/tags/v1.0.zip",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5373),
                            Price = 0m,
                            Title = "Elevators Managment"
                        },
                        new
                        {
                            ID = 7,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5413),
                            Description = "A B&B App writen in Java For Elevator Maintence Company.",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5422),
                            Price = 0m,
                            Title = "Elevators Dashboard"
                        },
                        new
                        {
                            ID = 8,
                            CreatedDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5459),
                            Description = "Update Your Old Vichecle To Full Software Update.",
                            LastUpdateDate = new DateTime(2022, 3, 4, 22, 1, 58, 290, DateTimeKind.Local).AddTicks(5466),
                            Price = 0m,
                            Title = "Remote Auto Moto"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyWebSite.Areas.Identity.Data.MyWebSiteUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Image", b =>
                {
                    b.HasOne("MyWebSite.Data.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Order", b =>
                {
                    b.HasOne("MyWebSite.Data.Models.Project", "Project")
                        .WithMany("Orders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("MyWebSite.Data.Models.Project", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
